config/routes.rb
Rails.application.routes.draw do
  resources :borders
  
  get 'albums/create'
  get 'albums/update'

  root 'static_page#home'
  get    'signup'   => 'users#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create_facebook'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'all_show' => 'clubs#all_show'
  get '/favorite' => 'clubs#favorite_show'
  get 'create' => 'clubs#new'
  get 'clubs/view/:id' => 'clubs#view'
  get 'clubs/edit/:id' => 'clubs#edit'
  get 'clubs/delete/:id' => 'clubs#delete'
  get "/:category" => 'clubs#category_show'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:create, :destroy]
  resources :users
  resources :clubs
  resources :bookmarks
  resources :relationships,       only: [:create, :destroy]
  

end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    if logged_in?
      redirect_to all_show_path
    end
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/_footer.html.erb
<footer class ="container-center" id = "footer">
     <div class="container" >
     	<br>
    	<div class = "nav navbar-left">
    		<%= link_to "sejong university club", '#', id: "" %>
    	</div>
    	<div class = "nav navbar-right">
    		<p> copyright(c)2015 All Fatdog All rights reserved </p>
    	</div>
</footer>

app/views/static_page/_header.html.erb
<nav class="navbar navbar-inverse">
	<div class = "container-fluid" id = "header_nav_container">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="true">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	
		<% if current_user %>
			<div class= "nav navbar-header">
			  <%= link_to "세종대동아리.com", all_show_path , id: "logo" %>
			</div>

			<div class="navbar-collapse collapse in" id="bs-example-navbar-collapse-2" aria-expanded="true">
				<ul class="nav navbar-nav">
					<li class="dropdown">
				        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> 카테고리 <span class="caret"></span></a>
				        <ul class="dropdown-menu" role="menu">
				            <li><%= link_to "전체", all_show_path %></li>
						  	<li class="divider"></li>
						  	<li><a href="/favorite"> 즐겨찾기 </a></li>
						    <li class="divider"></li>
						    <li><a href="/연극"> 연 극 </a></li>
						    <li><a href="/문화"> 문 화 </a></li>
						    <li><a href="/체육"> 체 육 </a></li>
						    <li><a href="/학술"> 학 술 </a></li>
						    <li><a href="/봉사"> 봉 사 </a></li>
						    <li><a href="/종교"> 종 교 </a></li>
						</ul>
					</li>
				</ul>

				<div class= "nav navbar-right" id ="right_top_user">
				    <ul class="nav navbar-nav">
				      	<li>
						    <% if (user_admin?) %>
								<%= link_to "동아리 등록하기", create_path %>
								
				        <li><a href="#"> 신청하기 </a></li>
				        <li><%= link_to "자유게시판", borders_path %></li>
				        	<% end %>
						</li>
				        <li class="active"><%= link_to current_user.name, "#" %></li>
				        <li><%= link_to "로그아웃", signout_path, id: "sign_out" %></li>
				        
				    </ul>
				</div>
			</div>

		<% else %>
			<div class="nav navbar-left">
			  <%= link_to "세종대동아리.com", root_path , id: "logo" %>
			</div>
		<% end %>
	</div>
</nav>

app/views/static_page/home.html.erb
<% if current_user %>
	<!-- 로그인 했으면 all_show로 이동(컨트롤러) -->	
<% else %>
	<% flash.each do |message_type, message| %>
		<div class="alert alert-<%= message_type %> center"><%= message %></div>
	<% end %>
	<br>
	<h1 id ="center"><strong> Introduce Club in Sejong University. </strong></h1>

	<!-- 로그인 구간 -->
	<div class="jumbotron" id = "login">
		<div class = "container">
		  <div class="col-xs-4 col-xs-offset-8">
		  
		    <%= form_for(:session, url: login_path) do |f| %>

		      <div class = "form-group">
		      <%= f.label :이메일 %>
		      <%= f.email_field :email, class: 'form-control', placeholder: "email@example.com" %>
		      </div>

		      <div class = "form-group">
		      <%= f.label :비밀번호 %>
		      <%= f.password_field :password, class: 'form-control', placeholder: "비밀번호" %>
		      </div>

		      <%= f.submit "로 그 인", class: "col-xs-6 btn btn-primary" %>
		    <% end %>

		    <%= link_to "회원가입", signup_path, class: "col-xs-6 btn btn-default"%>

		    <%= link_to "페이스북 로그인", "/auth/facebook", class: "col-xs-12 btn btn-info",id: "sign_in"  %>
		  </div>
		</div>
	</div>

	<!-- 개발자 소개하는 구간 -->
		<div id = "develop_intro" >
			<h3><strong> Sejong Club Homepage Developer </strong></h3>
			<hr class = "featurette-divider">
				<div class = "col-xs-4 col" id = "intro1">
					<div class ="thumbnail">
						<div class="circular"></div>
						<h2> FatDog Club </h2>
						<p> one of Fatdog member </p>
					</div>
				</div>

				<div class = "col-xs-4" id = "intro2">
					<div class ="thumbnail">
						<div class="circular"></div>
						<h2> 김 동 섭 </h2>
						<p> one of Fatdog member </p>
					</div>
				</div>

				<div class = "col-xs-4" id = "intro3">
					<div class ="thumbnail">
						<div class="circular"></div>
						<h2> 추 요 한 </h2>
						<p> one of Fatdog member </p>
					</div>
				</div>
			</div>
 
<script type="text/javascript"> 
	$.blockUI({messages:"Now Loading..."});
</script>		
<% end %>