config/routes.rb
Rails.application.routes.draw do
  resources :borders
  
  get 'albums/create'
  get 'albums/update'

  root 'static_page#home'
  get    'signup'   => 'users#new'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#create_facebook'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'all_show' => 'clubs#all_show'
  get '/favorite' => 'clubs#favorite_show'
  get 'create' => 'clubs#new'
  get 'clubs/view/:id' => 'clubs#view'
  get 'clubs/edit/:id' => 'clubs#edit'
  get 'clubs/delete/:id' => 'clubs#delete'
  get "/:category" => 'clubs#category_show'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions, only: [:create, :destroy]
  resources :users
  resources :clubs
  resources :bookmarks
  resources :relationships,       only: [:create, :destroy]
  

end

app/models/border.rb
class Border < ActiveRecord::Base
	belongs_to :user
	validates :user_id, presence: true
	validates :content, presence: true, length: {maximum: 140}
	validates :title, presence: true
end

app/controllers/borders_controller.rb
class BordersController < ApplicationController
  before_action :set_border, only: [:show, :edit, :update, :destroy]

  # GET /borders
  # GET /borders.json
  def index
    @borders = Border.all.paginate(page: params[:page]).per_page(10)
  end

  # GET /borders/1
  # GET /borders/1.json
  def show
    #클리시 조회수를 위한 코드
    @border = Border.where("id = ?", params[:id]).first
    @border.update_column('count', @border.count+1) unless @border.count.nil?
  end

  # GET /borders/new
  def new
    @border = Border.new
  end

  # GET /borders/1/edit
  def edit
  end

  # POST /borders
  # POST /borders.json
  def create
    @border = current_user.borders.build(border_params)
    @border.count = 0

    if @border.save
      flash[:success] = "세종대 동아리 소개 홈페이지에 오신걸 환영합니다!"
      redirect_to borders_url
    else
      render :new
      render json: @border.errors
    end
  end

  # PATCH/PUT /borders/1
  # PATCH/PUT /borders/1.json
  def update
    
    if @border.update(border_params)
      flash[:success] = "세종대 동아리 소개 홈페이지에 오신걸 환영합니다!"
      redirect_to borders_url
    else
      render :edit
      render json: @border.errors
    end
    
  end

  # DELETE /borders/1
  # DELETE /borders/1.json
  def destroy
    @border.destroy
    flash[:success] = "세종대 동아리 소개 홈페이지에 오신걸 환영합니다!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_border
      @border = Border.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def border_params
      params.require(:border).permit(:content, :title)  
    end
end

app/helpers/borders_helper.rb
module BordersHelper
end

app/views/borders/_form.html.erb
<div class = "container">
  <%= form_for(@border) do |f| %>
    <% if @border.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@border.errors.count, "error") %> prohibited this border from being saved:</h2>

        <ul>
        <% @border.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
      <div class="field">
        <%= f.label :title, "제 목" %><br>
        <%= f.text_field :title %>
      </div>

      <div class="field">
        <%= f.label :content, "내 용" %><br>
        <%= f.text_area :content %>
      </div>
    

    <div class="actions">
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/borders/edit.html.erb
<div class = "container" id = "border_cover">
	<h1>자유 게시판 글수정</h1>

	<%= render 'form' %>

	<%= link_to 'Back', borders_path %>
</div>

app/views/borders/index.html.erb
<script type="text/javascript">
$(document).ready(function(){
  $(".border_toggle").hide();
  $(".border_title").click(function(){
    $(this).find(".border_toggle").slideToggle("slow");
  });
});
</script>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> center"><%= message %></div>
<% end %>

<div class = "container" id = "border_cover">
  <div class = "col-xs-10">
    <h1>자유 게시판</h1>
  </div>
  <div class = "col-xs-2" id = "border_new_write">
    <%= link_to '글쓰기', new_border_path, class: "btn btn-default" %>
  </div>

  <table class = "table table-striped table-hover">
    <thead>
      <tr>
        <th id = 'border_index_count'>번호</th>
        <th id = 'border_index_username'>작성자</th>
        <th id = 'border_index_title'>제 목</th>
        <th id = "border_index_center">날 짜</th>
        <th id = "border_index_center">조회</th>
      </tr>
    </thead>


    <tbody>
      <% @borders.each_with_index do |border, index| %>
        <tr class = "default">
          <td id = 'border_index_count'><%= index + 1 %></td>
          <td id = 'border_index_username'><%= border.user.name %></td>
          <td id = 'border_index_title' class = "border_title">
            <div><%= border.title %></div>
            <div class = "border_toggle">
            <br>
            <%= border.content %>
            <br><br>
            <%= link_to 'Edit', edit_border_path(border), class: "btn btn-default" %>
            <%= link_to 'Destroy', border, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
            </div>
          </td>
          
          <td id = "border_index_date">
            <%= border.updated_at.strftime("%Y-%m-%d") %>
          </td>

          <td id = "border_index_center"><%= border.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <br>

  <div id = "paginate_center">
    <%= will_paginate @borders, previous_label: "<<", next_label: ">>" %>
  </div>

</div>

app/views/borders/new.html.erb
<div class = "container" id = "border_cover">
	<h1>자유 게시판 글쓰기</h1>

	<%= render 'form' %>

</div>

app/views/borders/show.html.erb
<div class = "container" id = "border_cover">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Title:</strong>
	  <%= @border.title %>
	</p>

	<p>
	  <strong>Content:</strong>
	  <%= @border.content %>
	</p>


	<%= link_to 'Edit', edit_border_path(@border) %> |
	<%= link_to 'Destroy', borders_path, method: :delete, data: { confirm: 'Are you sure?' } %> |
	<%= link_to 'Back', borders_path %>
</div>